export { default as Navigation } from '@/components/layout/Navigation'
export { default as Footer } from '@/components/layout/Footer'
export { default as Hero } from '@/components/sections/Hero'
export { default as About } from '@/components/sections/About'
export { default as Services } from '@/components/sections/Services'
export { default as Contact } from '@/components/sections/Contact'
export { default as Cta } from '@/components/sections/Cta'